### ISSUE TITLE
Launching titles with Locale Emulator

### ISSUE THREAD

**Issue by Revan67** [KJNeko/Hydrus95#11]
Syntax for launching with Local Emulator 

`installpath\LEProc.exe -run {command}`

Based on defined install path in settings title does not launch just produces an error.

Thought that the spaces in the filename were an issue. wrapping the command in single quotes causes a crash, double quotes does nothing.

`KJ16609 — Today at 1:54 PM
OH
[1:54 PM]
so the first variable is 
lpApplicationName
[1:54 PM]
second is
lpCommandLine
[1:55 PM]
The lpApplicationName parameter can be NULL. In that case, the module name must be the first white space–delimited token in the lpCommandLine string`

Attached image with all Locale Emulator parameters.
![image_2023-02-28_144352926](https://user-images.githubusercontent.com/8174203/221975170-aeef95ed-e88b-4b0a-b3ff-576aa4b44af5.png)

**Comment by KJNeko** [comment]
Fix works in testing environment. Closing. Will show up in next release.

**Comment by KJNeko** [comment]
Verified working with new quote fix.
